apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    
    # {{- if .Values.jmxExporter.coordinator.enabled }}
    # - port: {{ .Values.jmxExporter.port | default 9933 }}
    #   targetPort: jmx-exporter
    #   protocol: TCP
    #   name: {{ .Values.jmxExporter.serviceMonitor.port | default "jmx-exporter" }}
    # {{- end }}
    
    {{- range $key, $value := .Values.coordinator.additionalExposedPorts }}
    - port: {{ $value.servicePort }}
      name: {{ $value.name }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
    component: coordinator
