{{- if gt (int .Values.server.workers) 0 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "trino.worker" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.workers }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "trino.name" . }}
      release: {{ .Release.Name }}
      component: worker
  
  # Template for cache
  {{- if or .Values.cache.enabled .Values.spillToDisk.enabled }}
  volumeClaimTemplates:
  {{- if .Values.cache.enabled }}
  - metadata:
      name: {{ template "trino.worker" . }}-cache
    {{- if .Values.cache.labels.enabled }}
      labels:
        {{- include "trino.labels" . | nindent 8 }}
    {{- end }}
    {{- with .Values.cache.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      {{- range .Values.cache.accessModes }}
      - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.cache.size | quote }}
      storageClassName: "{{ .Values.cache.storageClass }}"
  {{- end }}
  
  {{- if .Values.spillToDisk.enabled }}
  - metadata:
      name: {{ template "trino.worker" . }}-spill
    {{- if .Values.spillToDisk.labels.enabled }}
      labels:
        {{- include "trino.labels" . | nindent 8 }}
    {{- end }}
    {{- with .Values.spillToDisk.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      {{- range .Values.spillToDisk.accessModes }}
      - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.spillToDisk.size | quote }}
      storageClassName: "{{ .Values.spillToDisk.storageClass }}"
  {{- end }}
  {{- end }}
  
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  
  template:
    metadata:
      {{- if .Values.worker.annotations }}
      annotations:
      {{- tpl (toYaml .Values.worker.annotations) . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "trino.name" . }}
        release: {{ .Release.Name }}
        component: worker
        {{- if .Values.worker.labels }}
        {{- tpl (toYaml .Values.worker.labels) . | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- tpl (toYaml .Values.commonLabels) . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.worker.gracefulShutdown.enabled }}
      terminationGracePeriodSeconds: {{ .Values.worker.gracefulShutdown.terminationGracePeriodSeconds }}
      {{- end }}
      
      serviceAccountName: {{ include "trino.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
      {{- end }}
      {{- if .Values.shareProcessNamespace.worker }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace.worker }}
      {{- end }}
      volumes:
        # Mount configmap to config volume
        - name: config-volume
          configMap:
            name: {{ template "trino.worker" . }}
        # Mount catalog secret to catalog volume
        - name: catalog-volume
          secret:
            secretName: {{ .Values.server.catalogSecret }}
        - name: schemas-volume
          configMap:
            name: schemas-volume-worker
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
        {{- range .Values.worker.secretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}
      {{- if .Values.initContainers.worker }}
      initContainers:
      {{- tpl (toYaml .Values.initContainers.worker) . | nindent 6 }}
      {{- end }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          volumeMounts:
            # Config node.properties volume mount
            - name: config-volume
              mountPath: {{ .Values.server.config.path }}
            # Catalog volume mount
            - mountPath: {{ .Values.server.config.path }}/catalog
              name: catalog-volume
            - mountPath: {{ .Values.kafka.mountPath }}
              name: schemas-volume
            {{- range .Values.secretMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
            {{- range .Values.worker.secretMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
            
            {{- if .Values.cache.enabled }}
            - name: {{ template "trino.worker" . }}-cache
              mountPath: {{ .Values.cache.path }}
            {{- end }}
            
            {{- if .Values.spillToDisk.enabled }}
            - name: {{ template "trino.worker" . }}-spill
              mountPath: {{ .Values.spillToDisk.path }}
            {{- end }}
            
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
              
            {{- if .Values.jmxExporter.worker.enabled }}
            - name: jmx-exporter
              containerPort: {{ .Values.jmxExporter.port | default 9933 }}
              protocol: TCP
            {{- end }}
              
          {{- range $key, $value := .Values.worker.additionalExposedPorts }}
            - name: {{ $value.name }}
              containerPort: {{ $value.port }}
              protocol: {{ $value.protocol }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: {{ .Values.worker.livenessProbe.initialDelaySeconds | default 20 }}
            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.worker.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.worker.livenessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.worker.livenessProbe.successThreshold | default 1 }}
          readinessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: {{ .Values.worker.readinessProbe.initialDelaySeconds | default 20 }}
            periodSeconds: {{ .Values.worker.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.worker.readinessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.worker.readinessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.worker.readinessProbe.successThreshold | default 1 }}
          
          {{- if .Values.worker.gracefulShutdown.enabled }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "curl -u \"admin:\" -v -X PUT -d \'\"SHUTTING_DOWN\"\' -H \"Content-type: application/json\" http://localhost:8080/v1/info/state > /proc/1/fd/1"] 
          {{- end }}
          
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- if .Values.sidecarContainers.worker }}
        {{- toYaml .Values.sidecarContainers.worker | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
