{{- if .Values.rangerAuthorizationMatrix.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-ranger-authorization-matrix
  labels:
    app: apache-ranger
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: apache-ranger-authorization-matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-ranger
      release: {{ .Release.Name }}
      component: apache-ranger-authorization-matrix
  template:
    metadata:
      {{- if .Values.rangerAuthorizationMatrix.annotations }}
      annotations:
      {{- tpl (toYaml .Values.rangerAuthorizationMatrix.annotations) . | nindent 8 }}
      {{- end }}
      labels:
        app: apache-ranger
        release: {{ .Release.Name }}
        component: apache-ranger-authorization-matrix
    spec:
      containers:
        - name: {{ .Chart.Name }}-authorization-matrix
          image: "{{ .Values.rangerAuthorizationMatrix.image.repository }}:{{ .Values.rangerAuthorizationMatrix.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rangerAuthorizationMatrix.image.pullPolicy }}
          resources:
            {{- toYaml .Values.rangerAuthorizationMatrix.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.rangerAuthorizationMatrix.port }}
              protocol: TCP
          env:
            - name: RANGER_URL
              value: "http://{{ .Release.Name }}-admin-svc:{{ .Values.service.rangerAdmin.port }}"
            - name: UVICORN_HOST
              value: "0.0.0.0"
            - name: UVICORN_PORT
              value: "{{ .Values.service.rangerAuthorizationMatrix.port }}"
          {{- if .Values.rangerAuthorizationMatrix.startupProbe }}
          startupProbe: {{- .Values.rangerAuthorizationMatrix.startupProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.rangerAuthorizationMatrix.readinessProbe }}
          readinessProbe: {{- .Values.rangerAuthorizationMatrix.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.rangerAuthorizationMatrix.livenessProbe }}
          livenessProbe: {{- .Values.rangerAuthorizationMatrix.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
      {{- with .Values.rangerAuthorizationMatrix.nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rangerAuthorizationMatrix.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rangerAuthorizationMatrix.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}